#pragma once

#define     CHANNEL_START           0x00
#define     CHANNEL_END             0x0F
#define     DATA_BYTES_START        0x00
#define     DATA_BYTES_END          0x7F

namespace IVCLaserOrgan
{
	enum MIDI_MessageEnums
	{
		NOTE_OFF = 0,
		NOTE_ON,
		AFTERTOUCH,
		CONTINUOUS_CONTROLLER,
		PATCH_CHANGE,
		CHANNEL_PRESSURE,
		PITCH_BEND,
		SYSTEM_MESSAGE,
		NUMBER_OF_MESSAGE_ENUMS
	};

	enum MIDI_ErrorCodes
	{
		UNKNOWN_COMMAND = 2000,
		CHANNEL_ERROR,
		PARAMETER_ONE_ERROR,
		PARAMETER_TWO_ERROR
	};
}

namespace CustomSerial
{
	enum SERIAL_ErrorCodes
	{ 
		ALL_OK = 0,
		WARNING_WRITE_MISMATCH = 100,
		FAILED_TO_CONNECT = 1000,
		FAILED_TO_GET_COM_STATE,
		FAILED_TO_SET_COM_STATE,
		FAILED_TO_GET_TIMEOUTS,
		FAILED_TO_SET_TIMEOUTS,
		READ_FAILED_TO_SET_EVENT,
		READ_NO_MESSAGE_AVAILABLE,
		READ_FAILED_TO_GET_MESSAGE,
		READ_MESSAGE_SIZE_MISMATCH,
		UNKNOWN_ERROR = 9000
	};
}